language: node_js
sudo: true
node_js:
  - '4.2.3'
cache:
  directories:
    - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - npm install -g bower
  - bower install
script:
  - gulp karma